In [151]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('headbrain.csv')
print(dataset.shape)

X = dataset['Head Size(cm^3)'].values
X = np.apply_along_axis(lambda c: (c - c.min())/(c.max() - c.min()), 0, X)
Y = dataset['Brain Weight(grams)'].values
Y = np.apply_along_axis(lambda c: (c - c.min())/(c.max() - c.min()), 0, Y)
Y = np.reshape(Y, (len(Y), 1))

one = np.ones(len(X))

X = np.vstack((one, X)).T
print(X)


(237, 4)
[[1.         0.88406512]
 [1.         0.50222003]
 [1.         0.7602368 ]
 [1.         0.52146029]
 [1.         0.71879625]
 [1.         0.42673902]
 [1.         0.52540701]
 [1.         0.41391219]
 [1.         0.44055254]
 [1.         0.62259497]
 [1.         0.35668476]
 [1.         0.62802171]
 [1.         0.45387272]
 [1.         0.73408979]
 [1.         0.54859398]
 [1.         0.57030094]
 [1.         0.38332511]
 [1.         0.36803157]
 [1.         0.18500247]
 [1.         0.84065121]
 [1.         0.57128762]
 [1.         0.65416872]
 [1.         0.53478046]
 [1.         0.48840651]
 [1.         1.        ]
 [1.         0.84015787]
 [1.         0.64923532]
 [1.         0.64232856]
 [1.         0.36211149]
 [1.         0.71780957]
 [1.         0.52639369]
 [1.         0.53083374]
 [1.         0.6822891 ]
 [1.         0.71090281]
 [1.         0.70942279]
 [1.         0.53971386]
 [1.         0.39812531]
 [1.         0.50715343]
 [1.         0.30291071]
 [1.         0.3

In [152]:
def rmse(y_pred, y_act):
 
    n = len(y_act)
    rmse = np.sqrt((np.sum((y_act - y_pred) ** 2) / n)) 

    return rmse 

In [153]:
def regression(X_train, X_test, Y_train, Y_test, itr, l_rate):
    
    theta = np.zeros((X_train.shape[1], 1))
    c = l_rate / len(X_train)
    train_rmse = np.empty(itr)
    test_rmse = np.empty(itr)
    h_train = X_train @ theta


    for i in range(itr):
        theta = theta - c * (X_train.T @ (h_train - Y_train))
        h_train = X_train @ theta
        h_test = X_test @ theta

        train_rmse[i] = rmse(h_train, Y_train)
        test_rmse[i] = rmse(h_test, Y_test)
    
    print(theta)

    return train_rmse, test_rmse


In [154]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)
itr = 5000
l_rate = 0.001
train_rmse = np.empty(itr)
test_rmse = np.empty(itr)
train_rmse, test_rmse = regression(X_train, X_test, Y_train, Y_test, itr, l_rate)
print(train_rmse)
print(test_rmse)


[[0.36869324]
 [0.26086599]]
[0.51033728 0.50977611 0.50921568 ... 0.1413195  0.14131774 0.14131598]
[0.52299572 0.52242774 0.5218605  ... 0.1445495  0.14454787 0.14454624]
